export * from "./generated/api";
// Explicit type re-exports from generated types — excludes names already exported
// as Zod schema values in api.ts (e.g. UpsertTravelEntryBody) to avoid TS2308.
export type {
  Answer,
  AuthUser,
  AuthUserEnvelope,
  ContinentStat,
  Country,
  CountryDetail,
  CreateAnswerBody,
  CreateQuestionBody,
  CreateReviewBody,
  DestinationStat,
  ErrorResponse,
  FeedItem,
  FeedItemData,
  FeedItemType,
  GetCommunityFeedParams,
  HealthStatus,
  ListCountriesParams,
  ListDestinationsByPassportParams,
  ListVisasParams,
  OkResponse,
  PassportDestinationsResponse,
  PassportRank,
  PassportRankEntry,
  QuestionSummary,
  QuestionWithAnswers,
  QuestionWithAnswersQuestion,
  Review,
  ReviewsResponse,
  ReviewsResponseAvgRatings,
  StatsOverview,
  TravelEntry,
  UpsertTravelEntryBodyStatus,
  UserSnippet,
  VisaDetail,
  VisaListResponse,
  VisaSummary,
} from "./generated/types";
